encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author:
  name: 李剑
  email: 1076629390@qq.com
  link: http://crazylxr.github.io/
  # weibo: http://weibo.com/u/2344559062
  github: https://github.com/crazylxr
  github_username:  crazylxr.github.io
  # weibo_username:  BladeMasterCoder

# 站点信息
title : 萧然自我
description:
  一不小心迈入计算机行业，在程序猿的道路上艰难地前行，目标是成
  为一名优秀的全栈工程师或者说资深码农。对很多东西都充满兴趣，
  跑步游泳，近期目标是能跑半程马拉松，学会自由泳。
url: http://crazylxr.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/me.png
favicon : /assets/img/1.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 当任何时候觉得累<br>你的大脑就在进化<br> 当任何时候觉得轻松<br>你都在使用你的习惯<br>

# 首页除了最新文章外显示分类
cates:
- Essay
# - Python
# - OpenStack

# 中文本地化
locals:
   newest : 最新文章
